#!/bin/sh -e
#
# start/stop the wolserver daemon
#
### BEGIN INIT INFO
# Provides:               wolserver
# Required-Start:         $network $remote_fs
# Required-Stop:          $network $remote_fs
# Default-Start:          2 3 4 5
# Default-Stop:           0 1 6
# Short-Description:      Start wolserver
# Description:            wolserver description.
### END INIT INFO

USERID=pi
NAME=wolserver
DESC="WOL session server"
EXEC=exec
PYTHON="/usr/bin/python"
WOL_SERVER="/etc/init.d/WOLServer.py"

. /lib/lsb/init-functions

PIDFILE=$WOL_SERVER

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        log_daemon_msg "Starting $DESC "
        # if [ ps -ef | grep $WOL_SERVER ]; then
        # log_progress_msg "$NAME already running"
        # log_end_msg 0
        #else
         log_progress_msg $NAME
         su $USERID -c "$EXEC $PYTHON $WOL_SERVER & &>/dev/null"
         log_end_msg $?
        #fi
        ;;
  stop)
        # log_daemon_msg "Stopping $DESC "
        # log_progress_msg $NAME
        # if [ -e "$PIDFILE" ] > /dev/null; then
        # su  $USERID -c "$WOL_SERVER -kill & &>/dev/null"
        #  log_end_msg $?
        #else
        # log_progress_msg "not running"
        # log_end_msg 0
        #fi
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME {start|stop}"
        exit 1
        ;;
esac

exit 0
